# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movieBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 3, 6, 9, 35, 884881, tzinfo=utc)),
        ),
    ]
