# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBlog', '0002_auto_20170103_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
