# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBlog', '0003_auto_20170103_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='In Progress'),
        ),
    ]
