# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieBlog', '0006_auto_20170110_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieBlog.Post'),
        ),
    ]
