# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBlog', '0007_auto_20170110_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
